<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class CarsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
      $data = [
        [
          'showroam_name' => 'Showroam Kendaraan Sedan',
          'brand' => 'Nissan Corolla 1998',
          'price' => 'Rp 53.000.000',
          'type_car' => 'Sedan',
          'type_engine' => 'In-Line 4 Cylinder',
          'oil_capacity' => '49 Liter',
          'fuel' => '2800cc',
          'engine_power' => '134 hp @5100 rpm',
          'type_transmission' => 'Manual 5-Speed',
          'type_turbo' => '-',
          'car_image' => 'Corolla1998.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sedan',
          'brand' => 'Mercedes Tiger',
          'price' => 'Rp 75.000.000',
          'type_car' => 'Sedan',
          'type_engine' => 'In-Line 6 Cylinder',
          'oil_capacity' => '75 Liter',
          'fuel' => '1800cc',
          'engine_power' => '120 hp @5600 rpm',
          'type_transmission' => 'Manual 5-Speed',
          'type_turbo' => '-',
          'car_image' => 'tiger.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sedan',
          'brand' => 'Chrysler 5th Avenue',
          'price' => 'Rp 51.000.000',
          'type_car' => 'Sedan',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '57 Liter',
          'fuel' => '5210cc',
          'engine_power' => '142 hp @4000 rpm',
          'type_transmission' => 'Automatic 3-Speed',
          'type_turbo' => '-',
          'car_image' => 'avenue.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sedan',
          'brand' => 'BMW E30 1991',
          'price' => 'Rp 404.621.000',
          'type_car' => 'Sedan',
          'type_engine' => 'V-Engine 6 Cylinder',
          'oil_capacity' => '64 Liter',
          'fuel' => '2494cc',
          'engine_power' => '170 hp @5800 rpm',
          'type_transmission' => 'Manual 5-Speed',
          'type_turbo' => '-',
          'car_image' => 'bmwe30.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan American Muscle',
          'brand' => 'Dodge Charger R/T 1970',
          'price' => 'Rp 470.820.000',
          'type_car' => 'American Muscle',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '72 Liter',
          'fuel' => '7206cc',
          'engine_power' => '375 hp @4600 rpm',
          'type_transmission' => 'Manual 4-Speed',
          'type_turbo' => 'Supercharger 35 psi',
          'car_image' => 'charger1970.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan American Muscle',
          'brand' => 'Dodge Challenger SRT Demon',
          'price' => 'Rp 1.500.000.000',
          'type_car' => 'American Muscle',
          'type_engine' => 'V-Enginge 8 Cylinder',
          'oil_capacity' => '84 Liter',
          'fuel' => '6162cc',
          'engine_power' => '808 hp @6300 rpm',
          'type_transmission' => 'Automatic 8-Speed',
          'type_turbo' => 'Supercharger 22 psi',
          'car_image' => 'demon.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan American Muscle',
          'brand' => 'Plymouth GTX 1971',
          'price' => 'Rp 690.457.000',
          'type_car' => 'American Muscle',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '78.7 Liter',
          'fuel' => '7210cc',
          'engine_power' => '385 hp @4200 rpm',
          'type_transmission' => 'Automatic 3-Speed',
          'type_turbo' => 'Supercharger 25.3 psi',
          'car_image' => 'gtx.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan American Muscle',
          'brand' => 'Ford Mustang GT 2005',
          'price' => 'Rp 359.392.000',
          'type_car' => 'American Muscle',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '60.5 Liter',
          'fuel' => '5000cc',
          'engine_power' => '300 hp @5750 rpm',
          'type_transmission' => 'Manual 5-Speed',
          'type_turbo' => 'Supercharger 32 psi',
          'car_image' => 'mustang.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan American Muscle',
          'brand' => 'Chevrolet Camaro SS 2020',
          'price' => 'Rp 365.000.000',
          'type_car' => 'American Muscle',
          'type_engine' => 'v-Engine 8 Cylinder',
          'oil_capacity' => '72 Liter',
          'fuel' => '9373cc',
          'engine_power' => '455 hp @6000 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => 'Supercharger 36 psi',
          'car_image' => 'camaross.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan SUV',
          'brand' => 'Audi Q3 Sportback',
          'price' => 'Rp 1.185.000.000',
          'type_car' => 'SUV',
          'type_engine' => 'In-Line Engine 4 Cylinder',
          'oil_capacity' => '58 Liter',
          'fuel' => '1395cc',
          'engine_power' => '455 hp @5000 rpm',
          'type_transmission' => 'Automatic 7-Speed',
          'type_turbo' => 'Turbo Standar',
          'car_image' => 'audiq3.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan SUV',
          'brand' => 'Jeep Grand Cherokee 2015',
          'price' => 'Rp 1.755.000.000',
          'type_car' => 'SUV',
          'type_engine' => 'V-Engine 6 Cylinder',
          'oil_capacity' => '93 Liter',
          'fuel' => '3000cc',
          'engine_power' => '294 hp @6400 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => '-',
          'car_image' => 'cherokee.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan SUV',
          'brand' => 'Land Rover-Range Rover',
          'price' => 'Rp 1.544.000.000',
          'type_car' => 'SUV',
          'type_engine' => 'Diesel In-Line Engine 4 Cylinder',
          'oil_capacity' => '67 Liter',
          'fuel' => '2996cc',
          'engine_power' => '434 hp @5500 rpm',
          'type_transmission' => 'Automatic 9-Speed',
          'type_turbo' => '-',
          'car_image' => 'rr.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan SUV',
          'brand' => 'Mitsubishi Pajero Sport',
          'price' => 'Rp 650.000.000',
          'type_car' => 'SUV',
          'type_engine' => 'Diesel In-Line Engine 4 Cylinder',
          'oil_capacity' => '68 Liter',
          'fuel' => '2477cc',
          'engine_power' => '179 hp @4000 rpm',
          'type_transmission' => 'Automatic 8-Speed',
          'type_turbo' => 'Turbo Standar',
          'car_image' => 'pajero.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan SUV',
          'brand' => 'Isuzu MU-X',
          'price' => 'Rp 600.000.000',
          'type_car' => 'SUV',
          'type_engine' => 'Diesel In-Line 4 Cylinder',
          'oil_capacity' => '80 Liter',
          'fuel' => '1898cc',
          'engine_power' => '148 hp @3600 rpm',
          'type_transmission' => 'Automatic 6-Speed',
          'type_turbo' => 'Supercharger 36 psi',
          'car_image' => 'isuzumux.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sport',
          'brand' => 'BMW M3 GTR',
          'price' => 'Rp 4.708.200.000',
          'type_car' => 'Sport',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '61 Liter',
          'fuel' => '3997cc',
          'engine_power' => '450 hp @7000 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => 'Turbo charger 32 psi',
          'car_image' => 'm3.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sport',
          'brand' => 'Mazda RX-7',
          'price' => 'Rp 430.847.000',
          'type_car' => 'Sport',
          'type_engine' => 'Twin-Chamber Rotary',
          'oil_capacity' => '75 Liter',
          'fuel' => '1146cc',
          'engine_power' => '240 hp @6500 rpm',
          'type_transmission' => 'Manual 5-Speed',
          'type_turbo' => 'Twin-Turbo 20 psi',
          'car_image' => 'rx7.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sport',
          'brand' => 'Nissan Skyline GTR R-34',
          'price' => 'Rp 1.925.606.000',
          'type_car' => 'Sport',
          'type_engine' => 'RB-26 Engine 6 Cylinder',
          'oil_capacity' => '65 Liter',
          'fuel' => '2600cc',
          'engine_power' => '280 hp @5600 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => 'Twin Turbo 35 psi',
          'car_image' => 'skyliner34.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sport',
          'brand' => 'Mitsubishi Lancer Evo X',
          'price' => 'Rp 2.511.040.000',
          'type_car' => 'Sport',
          'type_engine' => 'In-Line 4 Cylinder',
          'oil_capacity' => '55 Liter',
          'fuel' => '1998cc',
          'engine_power' => '290 hp @6500 rpm',
          'type_transmission' => 'Automatic 6-Speed',
          'type_turbo' => 'Turbo Charger 20 psi',
          'car_image' => 'lancerx.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Sport',
          'brand' => 'Toyota Supra MK-4',
          'price' => 'Rp 2.051.000.000',
          'type_car' => 'Sport',
          'type_engine' => '2JZ Engine 6 Cylinder',
          'oil_capacity' => '80 Liter',
          'fuel' => '3000cc',
          'engine_power' => '330 hp @5600 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => 'Twin Turbo 30 psi',
          'car_image' => 'mk4.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Supercar',
          'brand' => 'Porsche Carrera GT',
          'price' => 'Rp 20.402.200.000',
          'type_car' => 'Supercar',
          'type_engine' => 'V-Engine 10 Cylinder',
          'oil_capacity' => '92 Liter',
          'fuel' => '5733cc',
          'engine_power' => '605 hp @8000 rpm',
          'type_transmission' => 'Manual 6-Speed',
          'type_turbo' => 'Twin Turbo 13 psi',
          'car_image' => 'carreragt.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Supercar',
          'brand' => 'W-Motor Lykan Hypersport',
          'price' => 'Rp 53.359.600.000',
          'type_car' => 'Supercar',
          'type_engine' => 'Flat Engine 6 Cylinder',
          'oil_capacity' => '75 Liter',
          'fuel' => '3746cc',
          'engine_power' => '780 hp @7100 rpm',
          'type_transmission' => 'Manual Sequential 6-Speed',
          'type_turbo' => 'Twin Turbo 28 psi',
          'car_image' => 'lykan.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Supercar',
          'brand' => 'Chevrolet Corvette ZR1',
          'price' => 'Rp 2.356.132.500',
          'type_car' => 'Supercar',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '70 Liter',
          'fuel' => '6162cc',
          'engine_power' => '755 hp @6400 rpm',
          'type_transmission' => 'Manual 7-Speed',
          'type_turbo' => 'Supercharger 14 psi',
          'car_image' => 'corvettezr1.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Supercar',
          'brand' => 'Koenigsegg Jesko Absolut',
          'price' => 'Rp 44.570.960.000',
          'type_car' => 'Supercar',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '72 Liter',
          'fuel' => '5065cc',
          'engine_power' => '1280hp @7800 rpm',
          'type_transmission' => 'Light Speed 9-Speed',
          'type_turbo' => 'Twin Turbo 31 psi',
          'car_image' => 'jesko.png',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Supercar',
          'brand' => 'Bugatti Chiron',
          'price' => 'Rp 60.043.128.000',
          'type_car' => 'Supercar',
          'type_engine' => 'W-Engine 16 Cylinder',
          'oil_capacity' => '100 Liter',
          'fuel' => '8000cc',
          'engine_power' => '1479 hp @6700 rpm',
          'type_transmission' => 'Dual-Clutch Automatic 7-Speed',
          'type_turbo' => 'Quad-Turbo 27 psi',
          'car_image' => 'chiron.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Off-Road',
          'brand' => 'Toyota Land Cruise 1990',
          'price' => 'Rp 157.075.500',
          'type_car' => 'Off-Road',
          'type_engine' => 'In-Line 6 Cylinder',
          'oil_capacity' => '95 Liter',
          'fuel' => '3955cc',
          'engine_power' => '155 hp @4200 rpm',
          'type_transmission' => 'Automatic 6-Speed',
          'type_turbo' => '-',
          'car_image' => 'cruise.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Off-Road',
          'brand' => 'Hummer H2',
          'price' => 'Rp 785.377.500',
          'type_car' => 'Off-Road',
          'type_engine' => 'V-Engine 8 Cylinder',
          'oil_capacity' => '121 Liter',
          'fuel' => '6162cc',
          'engine_power' => '398 hp @5700 rpm',
          'type_transmission' => 'Automatic 6-Speed',
          'type_turbo' => '-',
          'car_image' => 'h2.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Off-Road',
          'brand' => 'Land Rover: Defender',
          'price' => 'Rp 2.016.000.000',
          'type_car' => 'Off-Road',
          'type_engine' => 'In-Line 6 Cylinder',
          'oil_capacity' => '89 Liter',
          'fuel' => '4997cc',
          'engine_power' => '295 hp @4000 rpm',
          'type_transmission' => 'Automatic 8-Speed',
          'type_turbo' => '-',
          'car_image' => 'defender.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Off-Road',
          'brand' => 'Chevrolet Colorado ZR2 Bison',
          'price' => 'Rp 942.453.000',
          'type_car' => 'Off-Road',
          'type_engine' => 'Diesel In-Line 4 Cylinder',
          'oil_capacity' => '81 Liter',
          'fuel' => '2800cc',
          'engine_power' => '310 hp @5600 rpm',
          'type_transmission' => 'Automatic 8-Speed',
          'type_turbo' => '-',
          'car_image' => 'colorado.jpg',
          'car_video' => '-',
        ],
        [
          'showroam_name' => 'Showroam Kendaraan Off-Road',
          'brand' => 'Jeep Wrangler Rubicon',
          'price' => 'Rp 1.730.000.000',
          'type_car' => 'Off-Road',
          'type_engine' => 'In-Line Engine 6 Cylinder',
          'oil_capacity' => '81 Liter',
          'fuel' => '1995cc',
          'engine_power' => '285 hp @6400 rpm',
          'type_transmission' => 'Automatic 8-Speed',
          'type_turbo' => '-',
          'car_image' => 'rubicon.png',
          'car_video' => '-',
        ],
      ];
    

      $posts = $this->table('cars_detail');
      $posts->insert($data)->saveData();

      // empty data
      // $posts -> truncate();
    }
}
